define(function() {
    return {
        "properties": [{
            "name": "title",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object2IsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backgroundSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object1IsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "description",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object1src",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "descriptionSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object2Src",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object1Top",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object2Top",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object1Animate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object2Animate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["show", "hide"],
        "events": []
    }
});